name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: | 
          cd kawaii_swipe_app 
          npm ci

      - name: Build production bundle
        run: | 
          cd kawaii_swipe_app  
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.MY_SECRET }}
          publish_dir: kawaii_swipe_app/build  
          publish_branch: gh-pages
